### ISSUE TITLE
User database file not accessible

### ISSUE THREAD

**Issue by t40mas** [tale/headplane#164]
### Description

Something is wrong in version 0.5.6.

`headplane  | 2025-04-02T20:49:32.232Z [server] INFO: Running Node.js 22.14.0
headplane  | 2025-04-02T20:49:32.244Z [config] INFO: Found a valid configuration file at /etc/headplane/config.yaml
headplane  | 2025-04-02T20:49:32.264Z [config] INFO: Found a valid Headscale configuration file at /etc/headscale/config.yaml
headplane  | 2025-04-02T20:49:32.269Z [config] INFO: User database file not accessible at /var/lib/headplane/users.json
headplane  | (node:1) ExperimentalWarning: SQLite is an experimental feature and might change at any time
headplane  | (Use `node --trace-warnings ...` to show where the warning was created)`

### Headplane Version

0.5.6

### Headscale Version

v0.25.1

**Comment by tale** [comment]
It should be fixed in `0.5.7` and this file should be stored persistently. All of `/var/lib/headplane` should be stored.

**Comment by t40mas** [comment]
Unfortunately version 0.5.7 doesn't solve my problem. Should the headplane container have a volume? I didn't find it in the example.

**Comment by t40mas** [comment]
Now headplane runs fine, but I'm stuck in the onboarding process and my users are gone.
Unfortunately i created my users by myself without oidc.

**Comment by tale** [comment]
Are you not using OIDC on the Headscale side? This is an interesting configuration and I would recommend downgrading to 0.5.5 and removing the `oidc.user_storage.file` value from your config for the time being.

**Comment by t40mas** [comment]
I had no usecase for oidc. It's just me, my homelab and some vps 😀

**Comment by tale** [comment]
It shouldn't onboard unless you have OIDC enabled. If you are logging in via API key, it wil skip that process.

**Comment by tale** [comment]
@t40mas `0.5.8` allows skipping onboarding if you would like to try that.

**Comment by t40mas** [comment]
Thank you very much for your support and your work! When I return from vacation, I will set up my Gitea as an OIDC provider.
